services:
  # --- RSSHub ---
  rsshub:
    image: diygod/rsshub:latest
    container_name: ${APP_PREFIX:-sp-}rsshub
    restart: unless-stopped
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://:${REDIS_PASSWORD:-redispassword}@redis:6379/"
    depends_on:
      - redis
    networks:
      - kb-network

  # ===========================================================================
  #  Knowledge Management (全栈 Web 项目)
  #  仓库结构: backend/ (Flask) + frontend/ (Vite+Nginx)
  #  GitHub: https://github.com/singll/knowledge-management
  # ===========================================================================

  # --- Backend (Flask API) ---
  km-backend:
    build:
      context: ./knowledge-management/backend
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX:-sp-}km-backend
    restart: unless-stopped
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      - DATABASE_URL=sqlite:////app/data/knowledge.db
      - RAGFLOW_URL=http://ragflow:80
      - RAGFLOW_API_KEY=${RAGFLOW_API_KEY:-}
      - SECRET_KEY=${KM_SECRET_KEY:-change-me-in-production}
    ports:
      - "5000:5000"
    volumes:
      # 持久化 SQLite 数据库和临时上传文件
      - km-backend-data:/app/data
      - km-backend-temp:/tmp/ragflow_uploads
    depends_on:
      - ragflow
    networks:
      kb-network:
        # nginx.conf 中使用 backend:5000 作为上游
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # --- Frontend (Vite + Nginx) ---
  km-frontend:
    build:
      context: ./knowledge-management/frontend
      dockerfile: Dockerfile
    container_name: ${APP_PREFIX:-sp-}km-frontend
    restart: unless-stopped
    ports:
      - "8088:80"
    depends_on:
      km-backend:
        condition: service_healthy
    networks:
      - kb-network

volumes:
  km-backend-data:
  km-backend-temp:
