#!/bin/sh
# ==============================================================================
#  Bellkeeper 入口脚本 - 环境变量热加载
#
#  核心功能:
#    从挂载的 .env 文件动态加载环境变量
#    → docker compose restart 即可加载新配置, 无需 up -d 重建容器
#    → 不重建容器 = 数据卷天然持久, 数据库连接/配置不会丢失
# ==============================================================================

ENV_FILE="/app/config/.env"

log() { echo "[bellkeeper-init] $*"; }

# --- 从挂载的 .env 加载环境变量 ---
if [ -f "$ENV_FILE" ]; then
    log "Loading environment from mounted .env"
    set -a
    . "$ENV_FILE"
    set +a
else
    log "WARNING: No .env file at $ENV_FILE, using Docker env vars only"
fi

# --- 派生变量 (从 .env 原始值构造 Bellkeeper 所需的完整配置) ---
PREFIX="${APP_PREFIX:-sp-}"

# Server
export BELLKEEPER_SERVER_MODE="${BELLKEEPER_SERVER_MODE:-release}"
export BELLKEEPER_SERVER_HOST="${BELLKEEPER_SERVER_HOST:-0.0.0.0}"
export BELLKEEPER_SERVER_PORT="${BELLKEEPER_SERVER_PORT:-8080}"
export BELLKEEPER_SERVER_API_KEY="${BELLKEEPER_API_KEY:-}"

# Database (本机 PostgreSQL)
export BELLKEEPER_DATABASE_DRIVER="${BELLKEEPER_DATABASE_DRIVER:-postgres}"
export BELLKEEPER_DATABASE_HOST="${BELLKEEPER_DATABASE_HOST:-${PREFIX}bellkeeper-db}"
export BELLKEEPER_DATABASE_PORT="${BELLKEEPER_DATABASE_PORT:-5432}"
export BELLKEEPER_DATABASE_NAME="${BELLKEEPER_DATABASE_NAME:-bellkeeper}"
export BELLKEEPER_DATABASE_USER="${BELLKEEPER_DATABASE_USER:-bellkeeper}"
export BELLKEEPER_DATABASE_PASSWORD="${BELLKEEPER_DB_PASSWORD:-bellkeeper123}"

# RagFlow (跨服务器访问 knowledge)
export BELLKEEPER_RAGFLOW_BASE_URL="${BELLKEEPER_RAGFLOW_BASE_URL:-http://${KNOWLEDGE_HOST:-192.168.7.220}:8080}"
export BELLKEEPER_RAGFLOW_API_KEY="${RAGFLOW_API_KEY:-}"

# n8n (同机访问)
export BELLKEEPER_N8N_WEBHOOK_BASE_URL="${BELLKEEPER_N8N_WEBHOOK_BASE_URL:-http://${PREFIX}n8n:5678/webhook}"
export BELLKEEPER_N8N_API_BASE_URL="${BELLKEEPER_N8N_API_BASE_URL:-http://${PREFIX}n8n:5678/api/v1}"
export BELLKEEPER_N8N_API_KEY="${N8N_API_KEY:-}"

# LLM Proxy (由 bellkeeper.yaml 中 ${VAR} 引用)
export LLM_NEWAPI_BASE_URL="${LLM_NEWAPI_BASE_URL:-}"
export LLM_NEWAPI_API_KEY="${LLM_NEWAPI_API_KEY:-}"
export LLM_DEEPSEEK_API_KEY="${LLM_DEEPSEEK_API_KEY:-}"
export LLM_KIMI_API_KEY="${LLM_KIMI_API_KEY:-}"
export LLM_SILICONFLOW_API_KEY="${LLM_SILICONFLOW_API_KEY:-}"
export LLM_QWEN_API_KEY="${LLM_QWEN_API_KEY:-}"

# Matrix Bot Platform
export BELLKEEPER_MATRIX_HOMESERVER="${MATRIX_HOMESERVER:-}"
export MATRIX_HOMESERVER_URL="${MATRIX_HOMESERVER:-}"
export BELLKEEPER_MATRIX_BOT_USER_ID="${MATRIX_BOT_USER_ID:-}"
export BELLKEEPER_MATRIX_BOT_TOKEN="${MATRIX_BOT_TOKEN:-}"
export MATRIX_BOT_ACCESS_TOKEN="${MATRIX_BOT_TOKEN:-}"
export BELLKEEPER_MATRIX_BOT_DEVICE_ID="${MATRIX_BOT_DEVICE_ID:-BELLKEEPER_KEEPER}"
export BELLKEEPER_MATRIX_SYNC_TIMEOUT="${MATRIX_SYNC_TIMEOUT:-30000}"
export BELLKEEPER_MATRIX_COMMAND_PREFIX="${MATRIX_COMMAND_PREFIX:-!,！}"
export BELLKEEPER_MATRIX_MAX_RETRY="${MATRIX_MAX_RETRY:-3}"
export BELLKEEPER_MATRIX_ROOM_ALERTS="${MATRIX_ROOM_ALERTS:-}"
export BELLKEEPER_MATRIX_ROOM_DAILY="${MATRIX_ROOM_DAILY:-}"
export BELLKEEPER_MATRIX_ROOM_TODO="${MATRIX_ROOM_TODO:-}"
export BELLKEEPER_MATRIX_ROOM_QA="${MATRIX_ROOM_QA:-}"

# Memos (todo.txt 导出)
export BELLKEEPER_MEMOS_BASE_URL="${MEMOS_BASE_URL:-}"
export BELLKEEPER_MEMOS_API_TOKEN="${MEMOS_API_TOKEN:-}"

# Redis (同机访问)
export BELLKEEPER_REDIS_HOST="${BELLKEEPER_REDIS_HOST:-${PREFIX}redis}"
export BELLKEEPER_REDIS_PORT="${BELLKEEPER_REDIS_PORT:-6379}"
export BELLKEEPER_REDIS_PASSWORD="${REDIS_PASSWORD:-}"
export BELLKEEPER_REDIS_DB="${BELLKEEPER_REDIS_DB:-0}"

# NATS (同机访问)
export BELLKEEPER_NATS_URL="${NATS_URL:-nats://${PREFIX}nats:4222}"

# Crawl Queue
export BELLKEEPER_CRAWL_QUEUE_ENABLED="${CRAWL_QUEUE_ENABLED:-true}"
export BELLKEEPER_CRAWL_QUEUE_FIRECRAWL_WORKERS="${CRAWL_QUEUE_FIRECRAWL_WORKERS:-3}"
export BELLKEEPER_CRAWL_QUEUE_TRAFILATURA_WORKERS="${CRAWL_QUEUE_TRAFILATURA_WORKERS:-2}"
export BELLKEEPER_CRAWL_QUEUE_AUTO_WORKERS="${CRAWL_QUEUE_AUTO_WORKERS:-2}"
export BELLKEEPER_CRAWL_QUEUE_POLL_INTERVAL="${CRAWL_QUEUE_POLL_INTERVAL:-5}"
export BELLKEEPER_CRAWL_QUEUE_MAX_RETRIES="${CRAWL_QUEUE_MAX_RETRIES:-4}"
export BELLKEEPER_CRAWL_QUEUE_RETRY_BACKOFF_BASE="${CRAWL_QUEUE_RETRY_BACKOFF_BASE:-60}"
export BELLKEEPER_CRAWL_QUEUE_RETRY_BACKOFF_MAX="${CRAWL_QUEUE_RETRY_BACKOFF_MAX:-7200}"
export BELLKEEPER_CRAWL_QUEUE_DEAD_LETTER_THRESHOLD="${CRAWL_QUEUE_DEAD_LETTER_THRESHOLD:-6}"
export BELLKEEPER_CRAWL_QUEUE_PAYWALL_THRESHOLD="${CRAWL_QUEUE_PAYWALL_THRESHOLD:-2}"

# --- 清理: 移除 Bellkeeper 不需要的敏感变量 ---
unset REDIS_PASSWORD COUCHDB_SECRET N8N_PASSWORD N8N_ENCRYPTION_KEY

# --- 启动 Bellkeeper (exec 替换当前进程, bellkeeper 作为 PID 1) ---
log "Starting Bellkeeper..."
exec /app/bellkeeper serve
