#!/usr/bin/env bash
# ==============================================================================
# 隔离共享浏览器 profile 管理（可自主增删 N 个独立 profile）
#   list                          列出所有隔离 profile
#   add <name> [--port N]         新增并启动一个隔离 profile（默认端口 9224 起自增）
#   remove <name>                 停止并移除（保留 profile 目录，登录态不自动删）
#   render                        仅重新生成 Caddy 片段并 reload
#   apply                         按注册表渲染 + 拉起单元 + reload
# 机制：注册表 data/browser-profiles.json + 模板单元 silksec-shared-browser@.service
#       + Caddy 片段 edge-browser-profiles.caddy（由 edge-Caddyfile import）。
# primary profile（9222）由 silksec-shared-browser.service 承载，不在本脚本管辖。
# 需 root（systemctl / caddy reload / 建 profile 目录）。
# ==============================================================================
set -euo pipefail
BASE_DIR="${SEC_BASE_DIR:-/opt/silkspool/dsh}"
REG="${SEC_BROWSER_PROFILES:-$BASE_DIR/data/browser-profiles.json}"
SNIPPET="${SEC_BROWSER_SNIPPET:-$BASE_DIR/edge-browser-profiles.caddy}"
CADDYFILE="${SEC_BROWSER_CADDYFILE:-$BASE_DIR/edge-Caddyfile}"
HOST_JS="${SHARED_BROWSER_HOST:-/home/silkspool/日常/browser/shared-browser-host.mjs}"
LAUNCH="${SHARED_BROWSER_LAUNCH:-/home/silkspool/日常/browser/shared-browser-launch.sh}"
UNIT_SRC="${SEC_BROWSER_UNIT_SRC:-$BASE_DIR/silksec-shared-browser@.service}"
UNIT_DST="/etc/systemd/system/silksec-shared-browser@.service"
PROFILE_ROOT="${SEC_BROWSER_PROFILE_ROOT:-/home/silkspool/日常/browser/.profiles}"
MIN_PORT="${SEC_BROWSER_MIN_PORT:-9224}"
valid_name() { case "$1" in (*[!a-z0-9_-]*|'') return 1 ;; (*) return 0 ;; esac; }

need() { command -v "$1" >/dev/null 2>&1 || { echo "缺少命令: $1" >&2; exit 2; }; }
need python3

ensure_reg() {
  # 注册表只含 profile 名/端口/目录（无秘密），需 silkspool 进程可读
  [ -f "$REG" ] || echo '{"version":1,"profiles":[]}' > "$REG"
  chmod 644 "$REG"
}
ensure_snippet() { [ -f "$SNIPPET" ] || { : > "$SNIPPET"; chmod 644 "$SNIPPET"; } }
ensure_unit() {
  [ -f "$UNIT_DST" ] || { install -m 644 "$UNIT_SRC" "$UNIT_DST"; systemctl daemon-reload; }
}

render() {
  ensure_reg; ensure_snippet
  python3 - "$REG" "$SNIPPET" <<'PY'
import json, sys
reg, out = sys.argv[1], sys.argv[2]
data = json.load(open(reg, encoding='utf-8'))
lines = ["# generated by sec-browser-profiles.sh — do not edit"]
# primary（固定 9222）也统一到 /p/primary/，使所有 profile 同构
entries = [('primary', 9222)] + [(p['name'], int(p['port'])) for p in data.get('profiles', [])]
for name, port in entries:
    lines += [
        f"handle_path /p/{name}/* {{",
        "    handle / {",
        "        header Cache-Control \"no-store\"",
        "        root * /opt/silkspool/dsh/edge-static",
        "        rewrite / /browser.html",
        "        file_server",
        "    }",
        "    handle {",
        f"        reverse_proxy 127.0.0.1:{port} {{",
        "            header_up Host 192.168.7.107:9223",
        "        }",
        "    }",
        "}",
    ]
open(out, 'w', encoding='utf-8').write("\n".join(lines) + "\n")
PY
  reload_caddy
}

reload_caddy() {
  if systemctl is-active --quiet silksecagent-edge.service; then
    caddy reload --config "$CADDYFILE" --adapter caddyfile
  fi
}

next_port() {
  python3 - "$REG" "$MIN_PORT" <<'PY'
import json, sys
data = json.load(open(sys.argv[1], encoding='utf-8'))
used = {int(p['port']) for p in data.get('profiles', [])}
used |= {9222, 9223, 7777, 3080, 3081, 2019}
port = int(sys.argv[2])
while port in used:
    port += 1
print(port)
PY
}

cmd_list() {
  ensure_reg
  python3 - "$REG" <<'PY'
import json, sys
d = json.load(open(sys.argv[1], encoding='utf-8'))
rows = d.get('profiles', [])
print(f"{'primary':16} port=9222  path=/p/primary/  dir=/home/silkspool/日常/browser/.shared-browser-profile")
for p in rows:
    print(f"{p['name']:16} port={p['port']}  path=/p/{p['name']}/  dir={p['dir']}")
PY
}

cmd_add() {
  local name="" port=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --port) port="$2"; shift 2 ;;
      *) name="$1"; shift ;;
    esac
  done
  valid_name "$name" || { echo "非法 profile 名（仅 [a-z0-9_-]）: $name" >&2; exit 2; }
  [ "$name" = primary ] && { echo "primary 由现有服务承载，不可加入注册表" >&2; exit 2; }
  ensure_reg
  local exists
  exists=$(python3 - "$REG" "$name" <<'PY'
import json, sys
d = json.load(open(sys.argv[1], encoding='utf-8'))
print('yes' if any(p['name'] == sys.argv[2] for p in d.get('profiles', [])) else 'no')
PY
)
  [ "$exists" = yes ] && { echo "profile 已存在: $name" >&2; exit 2; }
  [ -n "$port" ] || port="$(next_port)"
  local dir="$PROFILE_ROOT/$name"
  python3 - "$REG" "$name" "$port" "$dir" <<'PY'
import json, sys
reg, name, port, dir_ = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4]
d = json.load(open(reg, encoding='utf-8'))
d.setdefault('profiles', []).append({'name': name, 'port': port, 'dir': dir_})
d['profiles'].sort(key=lambda x: x['name'])
open(reg, 'w', encoding='utf-8').write(json.dumps(d, ensure_ascii=False, indent=2) + "\n")
PY
  install -d -m 700 -o silkspool -g silkspool "$dir"
  ensure_unit
  render
  systemctl enable --now "silksec-shared-browser@$name.service"
  echo "已新增隔离 profile: $name (port=$port)  入口 /p/$name/"
  echo "URL: https://browser.silksecagent.singll.net/p/$name/"
}

cmd_remove() {
  local name="${1:-}"; valid_name "$name" || { echo "非法 profile 名" >&2; exit 2; }
  ensure_reg
  systemctl disable --now "silksec-shared-browser@$name.service" 2>/dev/null || true
  local dir
  dir=$(python3 - "$REG" "$name" <<'PY'
import json, sys
d = json.load(open(sys.argv[1], encoding='utf-8'))
row = next((p for p in d.get('profiles', []) if p['name'] == sys.argv[2]), None)
print(row['dir'] if row else '')
d['profiles'] = [p for p in d.get('profiles', []) if p['name'] != sys.argv[2]]
open(sys.argv[1], 'w', encoding='utf-8').write(json.dumps(d, ensure_ascii=False, indent=2) + "\n")
PY
)
  render
  echo "已移除隔离 profile: $name（保留目录 ${dir:-未知}，如需彻底删除请手工 rm -rf）"
}

cmd_apply() {
  ensure_reg; ensure_unit
  local names
  names="$(python3 - "$REG" <<'PY'
import json, sys
for p in json.load(open(sys.argv[1], encoding='utf-8')).get('profiles', []):
    print(p['name'])
PY
)"
  if [ -n "$names" ]; then
    while read -r n; do
      [ -n "$n" ] && systemctl enable --now "silksec-shared-browser@$n.service"
    done <<< "$names"
  fi
  render
}

case "${1:-list}" in
  list) shift || true; cmd_list "$@" ;;
  add) shift; cmd_add "$@" ;;
  remove|rm) shift; cmd_remove "$@" ;;
  render) render ;;
  apply) cmd_apply ;;
  *) echo "usage: $0 {list|add <name> [--port N]|remove <name>|render|apply}" >&2; exit 2 ;;
esac
