package engine

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/singll/silkspool/internal/config"
	"github.com/singll/silkspool/pkg/utils"
)

// KeyManager 负责 spool 管控 SSH 密钥的轮换与主机下线。
type KeyManager struct {
	baseDir    string
	cfg        *config.Config
	sshKey     string // 当前 canonical 私钥绝对路径
	sshPub     string // = sshKey + ".pub"
	knownHosts string
}

// NewKeyManager 创建密钥管理器。
func NewKeyManager(baseDir string) (*KeyManager, error) {
	cfg, err := config.LoadConfig(baseDir)
	if err != nil {
		return nil, fmt.Errorf("failed to load config: %w", err)
	}
	sshKey := resolveSSHKeyPath(cfg.Global.SSHKeyPath, baseDir)
	return &KeyManager{
		baseDir:    baseDir,
		cfg:        cfg,
		sshKey:     sshKey,
		sshPub:     sshKey + ".pub",
		knownHosts: filepath.Join(baseDir, "known_hosts"),
	}, nil
}

// RotateOptions 轮换选项。
type RotateOptions struct {
	NewKeyPath    string // 指定新私钥路径 (空则自动生成)
	KeepOldRemote bool   // 跳过移除远程旧公钥
	DryRun        bool   // 只验证可达性并打印计划，不修改任何内容
	AssumeYes     bool   // 跳过二次确认
}

// DecommissionOptions 下线选项。
type DecommissionOptions struct {
	PurgeConfig bool // 同时从 silkspool.yaml 删除该主机块
	AssumeYes   bool // 跳过二次确认
}

// hostAliases 返回排序后的主机别名列表 (保证输出/操作顺序稳定)。
func (m *KeyManager) hostAliases() []string {
	aliases := make([]string, 0, len(m.cfg.Hosts))
	for h := range m.cfg.Hosts {
		aliases = append(aliases, h)
	}
	sort.Strings(aliases)
	return aliases
}

// Rotate 在所有受管控主机上轮换 canonical SSH 密钥 (两阶段、全有或全无)。
func (m *KeyManager) Rotate(opts RotateOptions) error {
	hosts := m.hostAliases()
	if len(hosts) == 0 {
		utils.Warn("No managed hosts in config; nothing to rotate")
		return nil
	}

	if _, err := os.Stat(m.sshKey); err != nil {
		return fmt.Errorf("current SSH key not found at %s: %w", m.sshKey, err)
	}
	oldBody, err := pubKeyBody(m.sshPub)
	if err != nil {
		return err
	}

	utils.Step("SSH key rotation across %d host(s): %s", len(hosts), strings.Join(hosts, ", "))

	// ---- Dry run: 仅用旧 key 验证可达性 ----
	if opts.DryRun {
		utils.Info("[dry-run] No changes will be made.")
		var unreachable []string
		for _, h := range hosts {
			hc := m.cfg.GetHost(h)
			if err := m.verifyKey(hc.Address, m.sshKey, hc); err != nil {
				unreachable = append(unreachable, h)
				utils.Error("  %-12s UNREACHABLE with current key: %v", h, err)
			} else {
				utils.Success("  %-12s reachable (%s)", h, hc.Address)
			}
		}
		utils.Info("")
		utils.Info("[dry-run] Would deploy a new key to all hosts, verify it, switch the local")
		utils.Info("[dry-run] canonical key (%s), then remove the old key from each host.", m.sshKey)
		if len(unreachable) > 0 {
			utils.Warn("[dry-run] %d host(s) unreachable: %s — rotation would ABORT.", len(unreachable), strings.Join(unreachable, ", "))
			utils.Warn("[dry-run] Decommission unreachable hosts first, then rotate.")
		} else {
			utils.Success("[dry-run] All hosts reachable — rotation can proceed safely.")
		}
		return nil
	}

	// ---- 确定新密钥 ----
	newKey := opts.NewKeyPath
	autoGenerated := false
	if newKey == "" {
		ts := time.Now().Format("20060102-150405")
		newKey = m.sshKey + ".new-" + ts
		utils.Info("Generating new ed25519 key: %s", newKey)
		if err := generateKeyPair(newKey, "silkspool-admin"); err != nil {
			return err
		}
		autoGenerated = true
	} else {
		abs, aerr := filepath.Abs(newKey)
		if aerr == nil {
			newKey = abs
		}
		if newKey == m.sshKey {
			return fmt.Errorf("--new must differ from the current canonical key (%s)", m.sshKey)
		}
		if _, err := os.Stat(newKey); err != nil {
			return fmt.Errorf("new private key not found: %s", newKey)
		}
		if _, err := os.Stat(newKey + ".pub"); err != nil {
			return fmt.Errorf("new public key not found: %s.pub", newKey)
		}
	}
	newPub := newKey + ".pub"
	newBody, err := pubKeyBody(newPub)
	if err != nil {
		return err
	}
	newLine, err := readPubLine(newPub)
	if err != nil {
		return err
	}
	if newBody == oldBody {
		return fmt.Errorf("new key is identical to the current key; nothing to rotate")
	}

	if !ConfirmDestructive("rotate the SSH key on", fmt.Sprintf("all %d managed host(s)", len(hosts)), opts.AssumeYes) {
		utils.Warn("Aborted")
		return nil
	}

	// ---- Phase A: 每台主机加新 key + 用新 key 验证 (旧 key 不动) ----
	utils.Step("Phase A: deploy and verify the new key on every host")
	var failed []string
	for _, h := range hosts {
		hc := m.cfg.GetHost(h)
		utils.Info("  [%s] %s", h, hc.Address)
		client, err := NewSSHClient(hc.Address, m.sshKey, m.clientOptsFor(hc)...)
		if err != nil {
			failed = append(failed, h)
			utils.Error("    connect with current key failed: %v", err)
			continue
		}
		if err := m.addKeyRemote(client, newLine, newBody); err != nil {
			client.Close()
			failed = append(failed, h)
			utils.Error("    deploy new key failed: %v", err)
			continue
		}
		client.Close()
		if err := m.verifyKey(hc.Address, newKey, hc); err != nil {
			failed = append(failed, h)
			utils.Error("    verify with new key failed: %v", err)
			continue
		}
		utils.Success("    new key deployed and verified")
	}

	if len(failed) > 0 {
		utils.Error("Phase A failed on %d host(s): %s", len(failed), strings.Join(failed, ", "))
		utils.Warn("Aborting before any key removal — the old key still works everywhere.")
		utils.Warn("The new key was harmlessly added on hosts that succeeded; fix the failures and re-run.")
		if autoGenerated {
			utils.Info("Generated new key kept at: %s (.pub: %s)", newKey, newPub)
		}
		return fmt.Errorf("rotation aborted: %d host(s) failed phase A", len(failed))
	}
	utils.Success("Phase A complete: new key verified on all %d host(s)", len(hosts))

	// ---- Phase B.1: 切换本地 canonical key ----
	utils.Step("Phase B: switch the local key, then remove the old key from hosts")
	backup, err := swapCanonicalKey(m.sshKey, newKey)
	if err != nil {
		return fmt.Errorf("failed to switch local canonical key: %w (new key is verified on all hosts — fix manually)", err)
	}
	utils.Success("Local key switched to the new key. Old key backed up: %s", backup)
	if autoGenerated {
		_ = os.Remove(newKey)
		_ = os.Remove(newPub)
	}

	if opts.KeepOldRemote {
		utils.Warn("--keep-old-remote: leaving the old key authorized on all hosts as a fallback")
		utils.Success("Rotation complete (old key retained remotely).")
		return nil
	}

	// ---- Phase B.2: 用新 (现 canonical) key 移除每台主机的旧公钥 ----
	var rmFail []string
	for _, h := range hosts {
		hc := m.cfg.GetHost(h)
		client, err := NewSSHClient(hc.Address, m.sshKey, m.clientOptsFor(hc)...)
		if err != nil {
			rmFail = append(rmFail, h)
			utils.Warn("  [%s] connect with new key failed: %v", h, err)
			continue
		}
		rmErr := m.removeKeyRemote(client, oldBody)
		client.Close()
		if rmErr != nil {
			rmFail = append(rmFail, h)
			utils.Warn("  [%s] remove old key failed: %v", h, rmErr)
		} else {
			utils.Success("  [%s] old key removed", h)
		}
	}
	if len(rmFail) > 0 {
		utils.Warn("Old key NOT removed on: %s (non-fatal — the new key is active everywhere)", strings.Join(rmFail, ", "))
		utils.Warn("Manually remove the line containing this key body from ~/.ssh/authorized_keys there:")
		utils.Warn("  %s", oldBody)
	}
	utils.Success("Rotation complete. New key active on all %d host(s).", len(hosts))
	return nil
}

// Decommission 吊销 spool 对某主机的访问，可选地从配置删除该主机。
func (m *KeyManager) Decommission(host string, opts DecommissionOptions) error {
	hc := m.cfg.GetHost(host)
	if hc == nil {
		return fmt.Errorf("unknown host: %s", host)
	}

	if !ConfirmDestructive("decommission (revoke spool SSH access from)", host, opts.AssumeYes) {
		utils.Warn("Aborted")
		return nil
	}

	body, err := pubKeyBody(m.sshPub)
	if err != nil {
		return err
	}

	utils.Step("Decommissioning %s (%s)", host, hc.Address)

	// 1. 吊销远程公钥
	client, err := NewSSHClient(hc.Address, m.sshKey, m.clientOptsFor(hc)...)
	if err != nil {
		utils.Warn("Cannot connect to %s: %v", host, err)
		utils.Warn("Host may already be unreachable; skipping remote key removal.")
	} else {
		rmErr := m.removeKeyRemote(client, body)
		client.Close()
		if rmErr != nil {
			utils.Warn("Remote key removal failed: %v", rmErr)
		} else {
			utils.Success("Revoked spool key from %s", host)
		}
	}

	// 2. 配置处理
	if opts.PurgeConfig {
		path, perr := config.ConfigFilePath(m.baseDir)
		if perr != nil {
			return perr
		}
		if err := config.RemoveHostFromYAML(path, host); err != nil {
			return fmt.Errorf("failed to purge config: %w", err)
		}
		utils.Success("Removed host %q from %s (backup: %s.bak)", host, path, path)
		utils.Info("Local dir hosts/%s/ left intact — remove it manually if no longer needed.", host)
	} else {
		utils.Info("")
		utils.Info("Config left unchanged. To finish removing %q from management:", host)
		utils.Info("  - delete the 'hosts.%s' block from silkspool.yaml (or re-run with --purge-config)", host)
		utils.Info("  - optionally remove the local dir: hosts/%s/", host)
	}

	utils.Success("Host %s decommissioned.", host)
	return nil
}

// Status 报告每台主机是否已授权当前 canonical 公钥。
func (m *KeyManager) Status(hosts []string) error {
	if len(hosts) == 0 {
		hosts = m.hostAliases()
	}
	if len(hosts) == 0 {
		utils.Warn("No managed hosts in config")
		return nil
	}
	body, err := pubKeyBody(m.sshPub)
	if err != nil {
		return err
	}
	utils.Step("Checking spool key authorization (key: %s)", m.sshPub)
	for _, h := range hosts {
		hc := m.cfg.GetHost(h)
		if hc == nil {
			utils.Warn("  %-12s unknown host", h)
			continue
		}
		client, err := NewSSHClient(hc.Address, m.sshKey, m.clientOptsFor(hc)...)
		if err != nil {
			utils.Error("  %-12s connect failed: %v", h, err)
			continue
		}
		out, exErr := client.Execute(buildCheckKeyScript(body))
		client.Close()
		if exErr != nil {
			utils.Error("  %-12s unreachable: %v", h, exErr)
			continue
		}
		if strings.Contains(out, "PRESENT") {
			utils.Success("  %-12s authorized (%s)", h, hc.Address)
		} else {
			utils.Warn("  %-12s reachable but key NOT in authorized_keys (%s)", h, hc.Address)
		}
	}
	return nil
}

// ==================== 远程 authorized_keys 操作 ====================

// clientOptsFor 返回连接指定主机的 SSH 选项。
func (m *KeyManager) clientOptsFor(hc *config.HostConfig) []SSHClientOption {
	port := hc.SSHPort
	if port == "" {
		port = "22"
	}
	return []SSHClientOption{
		WithSSHPort(port),
		WithKnownHosts(m.knownHosts),
	}
}

// addKeyRemote 幂等地把公钥追加到远程 authorized_keys (含 Dropbear)。
func (m *KeyManager) addKeyRemote(c *SSHClient, pubLine, body string) error {
	_, err := c.Execute(buildAddKeyScript(pubLine, body))
	return err
}

// removeKeyRemote 从远程 authorized_keys 移除匹配 body 的公钥行 (含 Dropbear)。
func (m *KeyManager) removeKeyRemote(c *SSHClient, body string) error {
	_, err := c.Execute(buildRemoveKeyScript(body))
	return err
}

// verifyKey 用指定私钥连接主机并执行探测命令，验证该 key 已被授权。
func (m *KeyManager) verifyKey(address, keyPath string, hc *config.HostConfig) error {
	c, err := NewSSHClient(address, keyPath, m.clientOptsFor(hc)...)
	if err != nil {
		return err
	}
	defer c.Close()
	out, err := c.Execute("echo spool-key-ok")
	if err != nil {
		return err
	}
	if !strings.Contains(out, "spool-key-ok") {
		return fmt.Errorf("unexpected verification output: %q", strings.TrimSpace(out))
	}
	return nil
}

// ==================== 脚本构建 ====================

// shSingleQuote 把字符串安全地用单引号包裹 (转义内部单引号)。
func shSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func buildAddKeyScript(pubLine, body string) string {
	return fmt.Sprintf(`KEYBODY=%s
PUBLINE=%s
add_to() {
  d=$(dirname "$1"); mkdir -p "$d"; chmod 700 "$d" 2>/dev/null || true
  touch "$1" 2>/dev/null || true; chmod 600 "$1" 2>/dev/null || true
  grep -qF "$KEYBODY" "$1" 2>/dev/null || printf '%%s\n' "$PUBLINE" >> "$1"
}
add_to "$HOME/.ssh/authorized_keys"
[ -d /etc/dropbear ] && add_to /etc/dropbear/authorized_keys || true
`, shSingleQuote(body), shSingleQuote(pubLine))
}

func buildRemoveKeyScript(body string) string {
	return fmt.Sprintf(`KEYBODY=%s
rm_from() {
  [ -f "$1" ] || return 0
  tmp="$1.spool.tmp"
  grep -vF "$KEYBODY" "$1" > "$tmp" 2>/dev/null || true
  cat "$tmp" > "$1" 2>/dev/null || true
  rm -f "$tmp"
}
rm_from "$HOME/.ssh/authorized_keys"
[ -d /etc/dropbear ] && rm_from /etc/dropbear/authorized_keys || true
`, shSingleQuote(body))
}

func buildCheckKeyScript(body string) string {
	return fmt.Sprintf(`if grep -qF %s "$HOME/.ssh/authorized_keys" 2>/dev/null || { [ -f /etc/dropbear/authorized_keys ] && grep -qF %s /etc/dropbear/authorized_keys 2>/dev/null; }; then echo PRESENT; else echo ABSENT; fi`,
		shSingleQuote(body), shSingleQuote(body))
}

// ==================== 本地密钥操作 ====================

// generateKeyPair 用 ssh-keygen 生成一对 ed25519 密钥。
func generateKeyPair(path, comment string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("failed to create key directory: %w", err)
	}
	// 预删除避免 ssh-keygen 交互式覆盖提示
	_ = os.Remove(path)
	_ = os.Remove(path + ".pub")
	cmd := exec.Command("ssh-keygen", "-t", "ed25519", "-f", path, "-N", "", "-C", comment)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ssh-keygen failed: %w", err)
	}
	_ = os.Chmod(path, 0600)
	return nil
}

// pubKeyBody 读取 .pub 文件并返回中间的 base64 主体字段。
func pubKeyBody(pubPath string) (string, error) {
	data, err := os.ReadFile(pubPath)
	if err != nil {
		return "", fmt.Errorf("failed to read public key %s: %w", pubPath, err)
	}
	fields := strings.Fields(string(data))
	if len(fields) < 2 {
		return "", fmt.Errorf("malformed public key: %s", pubPath)
	}
	return fields[1], nil
}

// readPubLine 读取 .pub 文件并返回去除首尾空白的完整公钥行。
func readPubLine(pubPath string) (string, error) {
	data, err := os.ReadFile(pubPath)
	if err != nil {
		return "", fmt.Errorf("failed to read public key %s: %w", pubPath, err)
	}
	line := strings.TrimSpace(string(data))
	if line == "" {
		return "", fmt.Errorf("empty public key: %s", pubPath)
	}
	return line, nil
}

// swapCanonicalKey 把 newKey 的内容写入 canonical 路径 curKey，
// 并把旧 canonical 密钥备份为 <curKey>.old-<时间戳>。返回备份私钥路径。
// 源 newKey 文件保持不变 (适用于 --new 指定的用户密钥)。
func swapCanonicalKey(curKey, newKey string) (string, error) {
	newPriv, err := os.ReadFile(newKey)
	if err != nil {
		return "", fmt.Errorf("failed to read new private key: %w", err)
	}
	newPub, err := os.ReadFile(newKey + ".pub")
	if err != nil {
		return "", fmt.Errorf("failed to read new public key: %w", err)
	}

	ts := time.Now().Format("20060102-150405")
	backup := curKey + ".old-" + ts

	// 备份旧 canonical (尽力而为)
	if oldPriv, err := os.ReadFile(curKey); err == nil {
		if werr := os.WriteFile(backup, oldPriv, 0600); werr != nil {
			return "", fmt.Errorf("failed to back up old private key: %w", werr)
		}
	}
	if oldPub, err := os.ReadFile(curKey + ".pub"); err == nil {
		_ = os.WriteFile(backup+".pub", oldPub, 0644)
	}

	// 原子写入新私钥到 canonical
	tmp := curKey + ".swap.tmp"
	if err := os.WriteFile(tmp, newPriv, 0600); err != nil {
		return "", fmt.Errorf("failed to stage new private key: %w", err)
	}
	if err := os.Rename(tmp, curKey); err != nil {
		return "", fmt.Errorf("failed to install new private key: %w", err)
	}

	// 原子写入新公钥
	tmpPub := curKey + ".pub.swap.tmp"
	if err := os.WriteFile(tmpPub, newPub, 0644); err != nil {
		return "", fmt.Errorf("failed to stage new public key: %w", err)
	}
	if err := os.Rename(tmpPub, curKey+".pub"); err != nil {
		return "", fmt.Errorf("failed to install new public key: %w", err)
	}

	return backup, nil
}
