services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: ${APP_PREFIX:-sp-}homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /opt/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro